<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    use HasFactory;
    protected $table= "projects";
    // protected $guarded = [];
    protected $fillable = [
        'project_logo',
        'project_name',
        'slug',
        'address',
        'project_location',
        'registered_company_name',
        'comapany_tax_number',
        'project_type',
        'project_duration_in_years',
        'accepted_currency',
        'starting_date',
        'accepted_currency',
        'delivery_date',
        'area_starting_per_sqm',
        'price_starting_per_sqm',
        'land_price_starting',
        'home_page_banner',
        'home_page_banner_text',
        'home_page_header_title',
        'home_page_header_paragraph',
        'home_page_footer_title',
        'home_page_footer_paragraph',
        'project_timeline',
        'project_management_companies',
        'home_page_photos_gallery',
        'qna_page_banner',
        'qna_page_banner_text',
        'qna_page_header_title',
        'qna_page_header_paragraph',
        'qna_page_footer_title',
        'qna_page_footer_paragraph',
        'buy_home_page_banner',
        'buy_home_page_banner_text',
        'buy_home_page_header_title',
        'buy_home_page_header_paragraph',
        'buy_home_page_footer_title',
        'buy_home_page_footer_paragraph',
        'buy_land_page_banner',
        'buy_land_page_banner_text',
        'buy_land_page_header_title',
        'buy_land_page_header_paragraph',
        'buy_land_page_footer_title',
        'buy_land_page_footer_paragraph',
        'amenities_page_banner',
        'amenities_page_banner_text',
        'amenities_page_header_title',
        'amenities_page_header_paragraph',
        'amenities_page_footer_title',
        'amenities_page_footer_paragraph',
        'financing_page_banner',
        'financing_page_banner_text',
        'financing_page_header_title',
        'financing_page_header_paragraph',
        'financing_page_footer_title',
        'financing_page_footer_paragraph',
        'who_page_banner',
        'who_page_banner_text',
        'who_page_header_title',
        'who_page_header_paragraph',
        'who_page_footer_title',
        'who_page_footer_paragraph',
        'contact_page_banner',
        'contact_page_banner_text',
        'contact_page_header_title',
        'contact_page_header_paragraph',
        'contact_page_footer_title',
        'contact_page_footer_paragraph',
        'kingsmen_details',
        'phone_number',
        'project_address',
        'email',
        'project_brochure',
        'project_elevations',
        'construction_rules',
        'other',
        'land_number',
        'land_category',
        'land_area',
        'land_price_per_sqm',
        'total_land_price',
        'interactive_map',
        'all_listings_land',
        'house_type',
        'house_area_per_sqm',
        'cost_of_construction_per_sqm',
        'all_listings_house',
        'technical_specs',
        'total_construction_cost',
        'selling_contract',
        'company_papers',
        'project_rules_and_regulation',
        'other_files',
        'project_thumbnail',
        'title',
        'description',
        'total_price_with_land',
        'deposit',
        'remainingAmount_as_bankTransfer',
        'full_payment_usdt',
        'template'
    ];

}
